USE [master]
GO
/****** Object:  Database [GI1819]    Script Date: 26/10/2018 17:13:42 ******/
CREATE DATABASE [GI1819]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GI1819', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\GI1819.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'GI1819_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\GI1819_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [GI1819] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GI1819].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GI1819] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GI1819] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GI1819] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GI1819] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GI1819] SET ARITHABORT OFF 
GO
ALTER DATABASE [GI1819] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [GI1819] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GI1819] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GI1819] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GI1819] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GI1819] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GI1819] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GI1819] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GI1819] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GI1819] SET  ENABLE_BROKER 
GO
ALTER DATABASE [GI1819] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GI1819] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GI1819] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GI1819] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GI1819] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GI1819] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GI1819] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GI1819] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GI1819] SET  MULTI_USER 
GO
ALTER DATABASE [GI1819] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GI1819] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GI1819] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GI1819] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [GI1819] SET DELAYED_DURABILITY = DISABLED 
GO
USE [GI1819]
GO
/****** Object:  User [alkesst]    Script Date: 26/10/2018 17:13:42 ******/
CREATE USER [alkesst] FOR LOGIN [alkesst] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  UserDefinedFunction [dbo].[esAdmin]    Script Date: 26/10/2018 17:13:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE FUNCTION [dbo].[esAdmin] (@n varchar(50), @p varchar(50))
RETURNS BIT
AS
BEGIN
DECLARE @Result BIT;

SELECT @Result = r.admin FROM tRol r, tUsuario u WHERE u.nombre=@n AND u.password=@p AND u.rolName=r.rolName; 

     IF @Result is NULL
     BEGIN
       set @Result = 0
     END

RETURN @Result;
END;



GO
/****** Object:  Table [dbo].[tAppointment]    Script Date: 26/10/2018 17:13:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tAppointment](
	[ID] [int] NOT NULL,
	[PatientSSNumber] [int] NOT NULL,
	[hourAndDate] [datetime] NULL,
	[Consultation] [varchar](50) NULL,
 CONSTRAINT [PK_tAppointment] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tCountry]    Script Date: 26/10/2018 17:13:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tCountry](
	[Code] [varchar](3) NOT NULL,
	[Description] [varchar](50) NULL,
 CONSTRAINT [PK_tCountry] PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tPatient]    Script Date: 26/10/2018 17:13:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tPatient](
	[SSNumber] [int] NOT NULL,
	[DNI] [varchar](50) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Surname] [varchar](50) NOT NULL,
	[Sex] [varchar](50) NOT NULL,
	[BornDate] [date] NOT NULL,
	[Direction] [varchar](50) NULL,
	[City] [varchar](50) NULL,
	[Province] [varchar](50) NULL,
	[PostalCode] [varchar](50) NULL,
	[Country] [varchar](3) NULL,
	[Telephone] [varchar](50) NULL,
	[email] [varchar](50) NOT NULL,
 CONSTRAINT [PK_tPatient] PRIMARY KEY CLUSTERED 
(
	[SSNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tPermiso]    Script Date: 26/10/2018 17:13:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tPermiso](
	[rolName] [varchar](50) NOT NULL,
	[pantalla] [varchar](50) NOT NULL,
	[acceso] [bit] NOT NULL,
	[modificacion] [bit] NOT NULL,
 CONSTRAINT [PK_tPermiso] PRIMARY KEY CLUSTERED 
(
	[rolName] ASC,
	[pantalla] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tRol]    Script Date: 26/10/2018 17:13:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tRol](
	[rolName] [varchar](50) NOT NULL,
	[rolDes] [varchar](255) NULL,
	[admin] [bit] NOT NULL,
 CONSTRAINT [PK_tRol] PRIMARY KEY CLUSTERED 
(
	[rolName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[tUsuario]    Script Date: 26/10/2018 17:13:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[tUsuario](
	[nombre] [varchar](50) NOT NULL,
	[password] [varchar](50) NOT NULL,
	[rolName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_tUsuario] PRIMARY KEY CLUSTERED 
(
	[nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[tAppointment]  WITH CHECK ADD  CONSTRAINT [FK_tAppointment_tPatient] FOREIGN KEY([PatientSSNumber])
REFERENCES [dbo].[tPatient] ([SSNumber])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tAppointment] CHECK CONSTRAINT [FK_tAppointment_tPatient]
GO
ALTER TABLE [dbo].[tPatient]  WITH CHECK ADD  CONSTRAINT [FK_tPatient_tCountry] FOREIGN KEY([Country])
REFERENCES [dbo].[tCountry] ([Code])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tPatient] CHECK CONSTRAINT [FK_tPatient_tCountry]
GO
ALTER TABLE [dbo].[tPermiso]  WITH CHECK ADD  CONSTRAINT [FK_tPermiso_tRol] FOREIGN KEY([rolName])
REFERENCES [dbo].[tRol] ([rolName])
GO
ALTER TABLE [dbo].[tPermiso] CHECK CONSTRAINT [FK_tPermiso_tRol]
GO
ALTER TABLE [dbo].[tUsuario]  WITH CHECK ADD  CONSTRAINT [FK_tUsuario_tRol] FOREIGN KEY([rolName])
REFERENCES [dbo].[tRol] ([rolName])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[tUsuario] CHECK CONSTRAINT [FK_tUsuario_tRol]
GO
/****** Object:  StoredProcedure [dbo].[InsertaUsuario]    Script Date: 26/10/2018 17:13:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[InsertaUsuario] (@u varchar(50), @p varchar(50), @u2 varchar(50), @p2 varchar(50), @r varchar(50) )
AS
BEGIN
     SET NOCOUNT ON;
     DECLARE @adm BIT

     EXEC @adm =  esAdmin @u, @p;
     PRINT @adm;
     IF @adm = 1
     BEGIN 
	INSERT INTO tUsuario VALUES(@u2,@p2,@r);
     END
END;

GO
USE [master]
GO
ALTER DATABASE [GI1819] SET  READ_WRITE 
GO

