USE [master]
GO
DROP DATABASE Prueba2
GO
CREATE DATABASE Prueba2
GO
USE Prueba2
GO

CREATE TABLE [dbo].[tPais](
	[Codigo] [varchar](3) NOT NULL,
	[Descripcion] [varchar](50) NULL,
 CONSTRAINT [PK_tPais] PRIMARY KEY CLUSTERED 
(
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[tProducto](
	[CODIGO] [int] NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[PAIS] [varchar](3) NOT NULL,
 CONSTRAINT [PK_Producto] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


ALTER TABLE [dbo].[tProducto]  WITH CHECK ADD  CONSTRAINT [FK_Producto_tPais] FOREIGN KEY([PAIS])
REFERENCES [dbo].[tPais] ([Codigo])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[tProducto] CHECK CONSTRAINT [FK_Producto_tPais]
GO


DELETE tPais;
GO
INSERT INTO tPais VALUES('ABW', 'ARUBA');
INSERT INTO tPais VALUES('AFG', 'AFGANISTÁN');
INSERT INTO tPais VALUES('AGO', 'ANGOLA');
INSERT INTO tPais VALUES('AIA', 'ANGUILA');
INSERT INTO tPais VALUES('ALA', 'ÅLAND');
INSERT INTO tPais VALUES('ALB', 'ALBANIA');
INSERT INTO tPais VALUES('AND', 'ANDORRA');
INSERT INTO tPais VALUES('ANT', 'ANTILLAS NEERLANDESAS');
INSERT INTO tPais VALUES('ARE', 'EMIRATOS ÁRABES UNIDOS');
INSERT INTO tPais VALUES('ARG', 'ARGENTINA');
INSERT INTO tPais VALUES('ARM', 'ARMENIA');
INSERT INTO tPais VALUES('ASM', 'SAMOA ESTADOUNIDENSE');
INSERT INTO tPais VALUES('ATG', 'ANTIGUA Y BARBUDA');
INSERT INTO tPais VALUES('AUS', 'AUSTRALIA');
INSERT INTO tPais VALUES('AUT', 'AUSTRIA');
INSERT INTO tPais VALUES('AZE', 'AZERBAIYÁN');
INSERT INTO tPais VALUES('BDI', 'BURUNDI');
INSERT INTO tPais VALUES('BEL', 'BÉLGICA');
INSERT INTO tPais VALUES('BEN', 'BENÍN');
INSERT INTO tPais VALUES('BFA', 'BURKINA FASO');
INSERT INTO tPais VALUES('BGD', 'BANGLADÉS');
INSERT INTO tPais VALUES('BGR', 'BULGARIA');
INSERT INTO tPais VALUES('BHR', 'BARÉIN');
INSERT INTO tPais VALUES('BHS', 'BAHAMAS');
INSERT INTO tPais VALUES('BIH', 'BOSNIA Y HERZEGOVINA');
INSERT INTO tPais VALUES('BLM', 'SAN BARTOLOMÉ');
INSERT INTO tPais VALUES('BLR', 'BIELORRUSIA');
INSERT INTO tPais VALUES('BLZ', 'BELICE');
INSERT INTO tPais VALUES('BMU', 'BERMUDAS');
INSERT INTO tPais VALUES('BOL', 'BOLIVIA');
INSERT INTO tPais VALUES('BRA', 'BRASIL');
INSERT INTO tPais VALUES('BRB', 'BARBADOS');
INSERT INTO tPais VALUES('BRN', 'BRUNÉI');
INSERT INTO tPais VALUES('BTN', 'BUTÁN');
INSERT INTO tPais VALUES('BVT', 'ISLA BOUVET');
INSERT INTO tPais VALUES('BWA', 'BOTSUANA');
INSERT INTO tPais VALUES('CAF', 'REPÚBLICA CENTROAFRICANA');
INSERT INTO tPais VALUES('CAN', 'CANADÁ');
INSERT INTO tPais VALUES('CCK', 'ISLAS COCOS');
INSERT INTO tPais VALUES('CHL', 'CHILE');
INSERT INTO tPais VALUES('CHN', 'CHINA');
INSERT INTO tPais VALUES('CIV', 'COSTA DE MARFIL');
INSERT INTO tPais VALUES('CMR', 'CAMERÚN');
INSERT INTO tPais VALUES('COD', 'REP. DEM. DEL CONGO');
INSERT INTO tPais VALUES('COG', 'REPÚBLICA DEL CONGO');
INSERT INTO tPais VALUES('COK', 'ISLAS COOK');
INSERT INTO tPais VALUES('COL', 'COLOMBIA');
INSERT INTO tPais VALUES('COM', 'COMORAS');
INSERT INTO tPais VALUES('CPV', 'CABO VERDE');
INSERT INTO tPais VALUES('CRI', 'COSTA RICA');
INSERT INTO tPais VALUES('CUB', 'CUBA');
INSERT INTO tPais VALUES('CXR', 'ISLA DE NAVIDAD');
INSERT INTO tPais VALUES('CYM', 'ISLAS CAIMÁN');
INSERT INTO tPais VALUES('CYP', 'CHIPRE');
INSERT INTO tPais VALUES('CZE', 'REPÚBLICA CHECA');
INSERT INTO tPais VALUES('DEU', 'ALEMANIA');
INSERT INTO tPais VALUES('DMA', 'DOMINICA');
INSERT INTO tPais VALUES('DNK', 'DINAMARCA');
INSERT INTO tPais VALUES('DOM', 'REPÚBLICA DOMINICANA');
INSERT INTO tPais VALUES('DZA', 'ARGELIA');
INSERT INTO tPais VALUES('ECU', 'ECUADOR');
INSERT INTO tPais VALUES('EGY', 'EGIPTO');
INSERT INTO tPais VALUES('ERI', 'ERITREA');
INSERT INTO tPais VALUES('ESH', 'REPÚBLICA ÁRABE SAHARAUI DEMOCRÁTICA');
INSERT INTO tPais VALUES('ESP', 'ESPAÑA');
INSERT INTO tPais VALUES('EST', 'ESTONIA');
INSERT INTO tPais VALUES('ETH', 'ETIOPÍA');
INSERT INTO tPais VALUES('FIN', 'FINLANDIA');
INSERT INTO tPais VALUES('FJI', 'FIYI');
INSERT INTO tPais VALUES('FLK', 'ISLAS MALVINAS');
INSERT INTO tPais VALUES('FRA', 'FRANCIA');
INSERT INTO tPais VALUES('FRO', 'ISLAS FEROE');
INSERT INTO tPais VALUES('FSM', 'MICRONESIA');
INSERT INTO tPais VALUES('GAB', 'GABÓN');
INSERT INTO tPais VALUES('GBR', 'REINO UNIDO');
INSERT INTO tPais VALUES('GEO', 'GEORGIA');
INSERT INTO tPais VALUES('GGY', 'GUERNSEY');
INSERT INTO tPais VALUES('GHA', 'GHANA');
INSERT INTO tPais VALUES('GIB', 'GIBRALTAR');
INSERT INTO tPais VALUES('GIN', 'GUINEA');
INSERT INTO tPais VALUES('GLP', 'GUADALUPE');
INSERT INTO tPais VALUES('GMB', 'GAMBIA');
INSERT INTO tPais VALUES('GNB', 'GUINEA-BISSAU');
INSERT INTO tPais VALUES('GNQ', 'GUINEA ECUATORIAL');
INSERT INTO tPais VALUES('GRC', 'GRECIA');
INSERT INTO tPais VALUES('GRD', 'GRANADA');
INSERT INTO tPais VALUES('GRL', 'GROENLANDIA');
INSERT INTO tPais VALUES('GTM', 'GUATEMALA');
INSERT INTO tPais VALUES('GUF', 'GUAYANA FRANCESA');
INSERT INTO tPais VALUES('GUM', 'GUAM');
INSERT INTO tPais VALUES('GUY', 'GUYANA');
INSERT INTO tPais VALUES('HKG', 'HONG KONG');
INSERT INTO tPais VALUES('HMD', 'ISLAS HEARD Y MCDONALD');
INSERT INTO tPais VALUES('HND', 'HONDURAS');
INSERT INTO tPais VALUES('HRV', 'CROACIA');
INSERT INTO tPais VALUES('HTI', 'HAITÍ');
INSERT INTO tPais VALUES('HUN', 'HUNGRÍA');
INSERT INTO tPais VALUES('IDN', 'INDONESIA');
INSERT INTO tPais VALUES('IMN', 'ISLA DE MAN');
INSERT INTO tPais VALUES('IND', 'INDIA');
INSERT INTO tPais VALUES('IRL', 'IRLANDA');
INSERT INTO tPais VALUES('IRN', 'IRÁN');
INSERT INTO tPais VALUES('IRQ', 'IRAK');
INSERT INTO tPais VALUES('ISL', 'ISLANDIA');
INSERT INTO tPais VALUES('ISR', 'ISRAEL');
INSERT INTO tPais VALUES('ITA', 'ITALIA');
INSERT INTO tPais VALUES('JAM', 'JAMAICA');
INSERT INTO tPais VALUES('JEY', 'JERSEY');
INSERT INTO tPais VALUES('JOR', 'JORDANIA');
INSERT INTO tPais VALUES('JPN', 'JAPÓN');
INSERT INTO tPais VALUES('KAZ', 'KAZAJISTÁN');
INSERT INTO tPais VALUES('KEN', 'KENIA');
INSERT INTO tPais VALUES('KGZ', 'KIRGUISTÁN');
INSERT INTO tPais VALUES('KHM', 'CAMBOYA');
INSERT INTO tPais VALUES('KIR', 'KIRIBATI');
INSERT INTO tPais VALUES('KNA', 'SAN CRISTÓBAL Y NIEVES');
INSERT INTO tPais VALUES('KOR', 'COREA DEL SUR');
INSERT INTO tPais VALUES('KWT', 'KUWAIT');
INSERT INTO tPais VALUES('LAO', 'LAOS');
INSERT INTO tPais VALUES('LBN', 'LÍBANO');
INSERT INTO tPais VALUES('LBR', 'LIBERIA');
INSERT INTO tPais VALUES('LBY', 'LIBIA');
INSERT INTO tPais VALUES('LCA', 'SANTA LUCÍA');
INSERT INTO tPais VALUES('LIE', 'LIECHTENSTEIN');
INSERT INTO tPais VALUES('LSO', 'LESOTO');
INSERT INTO tPais VALUES('LTU', 'LITUANIA');
INSERT INTO tPais VALUES('LUX', 'LUXEMBURGO');
INSERT INTO tPais VALUES('LVA', 'LETONIA');
INSERT INTO tPais VALUES('MAC', 'MACAO');
INSERT INTO tPais VALUES('MAF', 'SAN MARTÍN');
INSERT INTO tPais VALUES('MAR', 'MARRUECOS');
INSERT INTO tPais VALUES('MCO', 'MÓNACO');
INSERT INTO tPais VALUES('MDA', 'MOLDAVIA');
INSERT INTO tPais VALUES('MDG', 'MADAGASCAR');
INSERT INTO tPais VALUES('MDV', 'MALDIVAS');
INSERT INTO tPais VALUES('MEX', 'MÉXICO');
INSERT INTO tPais VALUES('MHL', 'ISLAS MARSHALL');
INSERT INTO tPais VALUES('MKD', 'REPÚBLICA DE MACEDONIA');
INSERT INTO tPais VALUES('MLI', 'MALÍ');
INSERT INTO tPais VALUES('MLT', 'MALTA');
INSERT INTO tPais VALUES('MMR', 'BIRMANIA');
INSERT INTO tPais VALUES('MNE', 'MONTENEGRO');
INSERT INTO tPais VALUES('MNG', 'MONGOLIA');
INSERT INTO tPais VALUES('MNP', 'ISLAS MARIANAS DEL NORTE');
INSERT INTO tPais VALUES('MOZ', 'MOZAMBIQUE');
INSERT INTO tPais VALUES('MRT', 'MAURITANIA');
INSERT INTO tPais VALUES('MSR', 'MONTSERRAT');
INSERT INTO tPais VALUES('MTQ', 'MARTINICA');
INSERT INTO tPais VALUES('MUS', 'MAURICIO');
INSERT INTO tPais VALUES('MWI', 'MALAUI');
INSERT INTO tPais VALUES('MYS', 'MALASIA');
INSERT INTO tPais VALUES('MYT', 'MAYOTTE');
INSERT INTO tPais VALUES('NAM', 'NAMIBIA');
INSERT INTO tPais VALUES('NCL', 'NUEVA CALEDONIA');
INSERT INTO tPais VALUES('NER', 'NÍGER');
INSERT INTO tPais VALUES('NFK', 'NORFOLK');
INSERT INTO tPais VALUES('NGA', 'NIGERIA');
INSERT INTO tPais VALUES('NIC', 'NICARAGUA');
INSERT INTO tPais VALUES('NIU', 'NIUE');
INSERT INTO tPais VALUES('NLD', 'PAÍSES BAJOS');
INSERT INTO tPais VALUES('NOR', 'NORUEGA');
INSERT INTO tPais VALUES('NPL', 'NEPAL');
INSERT INTO tPais VALUES('NRU', 'NAURU');
INSERT INTO tPais VALUES('NZL', 'NUEVA ZELANDA');
INSERT INTO tPais VALUES('OMN', 'OMÁN');
INSERT INTO tPais VALUES('PAK', 'PAKISTÁN');
INSERT INTO tPais VALUES('PAN', 'PANAMÁ');
INSERT INTO tPais VALUES('PCN', 'ISLAS PITCAIRN');
INSERT INTO tPais VALUES('PER', 'PERÚ');
INSERT INTO tPais VALUES('PHL', 'FILIPINAS');
INSERT INTO tPais VALUES('PLW', 'PALAOS');
INSERT INTO tPais VALUES('PNG', 'PAPÚA NUEVA GUINEA');
INSERT INTO tPais VALUES('POL', 'POLONIA');
INSERT INTO tPais VALUES('PRI', 'PUERTO RICO');
INSERT INTO tPais VALUES('PRK', 'COREA DEL NORTE');
INSERT INTO tPais VALUES('PRT', 'PORTUGAL');
INSERT INTO tPais VALUES('PRY', 'PARAGUAY');
INSERT INTO tPais VALUES('PSE', 'AUTORIDAD NACIONAL PALESTINA');
INSERT INTO tPais VALUES('PYF', 'POLINESIA FRANCESA');
INSERT INTO tPais VALUES('QAT', 'CATAR');
INSERT INTO tPais VALUES('REU', 'REUNIÓN');
INSERT INTO tPais VALUES('ROU', 'RUMANÍA');
INSERT INTO tPais VALUES('RUS', 'RUSIA');
INSERT INTO tPais VALUES('RWA', 'RUANDA');
INSERT INTO tPais VALUES('SAU', 'ARABIA SAUDITA');
INSERT INTO tPais VALUES('SEN', 'SENEGAL');
INSERT INTO tPais VALUES('SGS', 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR');
INSERT INTO tPais VALUES('SHN', 'SANTA HELENA, A. Y T.');
INSERT INTO tPais VALUES('SLB', 'ISLAS SALOMÓN');
INSERT INTO tPais VALUES('SLV', 'EL SALVADOR');
INSERT INTO tPais VALUES('SMR', 'SAN MARINO');
INSERT INTO tPais VALUES('SPM', 'SAN PEDRO Y MIQUELÓN');
INSERT INTO tPais VALUES('SRB', 'SERBIA');
INSERT INTO tPais VALUES('STP', 'SANTO TOMÉ Y PRÍNCIPE');
INSERT INTO tPais VALUES('SVK', 'ESLOVAQUIA');
INSERT INTO tPais VALUES('SVN', 'ESLOVENIA');
INSERT INTO tPais VALUES('TCD', 'CHAD');
INSERT INTO tPais VALUES('USA', 'ESTADOS UNIDOS');
INSERT INTO tPais VALUES('VCT', 'SAN VICENTE Y LAS GRANADINAS');
INSERT INTO tPais VALUES('WSM', 'SAMOA');
GO

INSERT INTO tProducto VALUES(1,'Producto1','ESP');
INSERT INTO tProducto VALUES(2,'Producto2','USA');
INSERT INTO tProducto VALUES(3,'Producto3','ESP');
INSERT INTO tProducto VALUES(4,'Producto4','USA');
INSERT INTO tProducto VALUES(5,'Producto5','USA');
INSERT INTO tProducto VALUES(6,'Producto6','ESP');
INSERT INTO tProducto VALUES(7,'Producto7','USA');
INSERT INTO tProducto VALUES(8,'Producto8','ESP');
INSERT INTO tProducto VALUES(9,'Producto9','USA');
INSERT INTO tProducto VALUES(10,'Producto10','USA');

GO
